class FigureFormatting:
	def __init__(self):
		inch=2.54
		self.std_paper_1x1_full_width = {'figsize': (16/inch, 6/inch),
							   			 'legend_size': 8,
							   			 'label_size': 8,
										 'tick_size': 8,
										 'tick_length': 3,
										 'tick_width': 1,
										 'tick_rotation': 45,
										 'spine_width': 1,
										 'line_width': 1,
										 'legend_length': 3,
										 'labelpad': 3,
										 'legend_frame_width': 0.5,
										 'legend_edge_color': 'dimgray'}

		self.std_paper_3x1_full_width = {'figsize': (16/inch, 12/inch),
							   			 'legend_size': 8,
							   			 'label_size': 8,
										 'tick_size': 8,
										 'tick_length': 3,
										 'tick_width': 1,
										 'tick_rotation': 45,
										 'spine_width': 1,
										 'hspace': 0.1,
										 'line_width': 1,
										 'legend_length': 3,
										 'labelpad': 3,
										 'legend_frame_width': 0.5,
										 'legend_edge_color': 'dimgray'}

		self.std_paper_3x1_partial_width = {'figsize': (10/inch, 12/inch),
							   			    'legend_size': 8,
							   			    'label_size': 8,
										    'tick_size': 8,
										    'tick_length': 3,
										    'tick_width': 1,
										    'tick_rotation': 45,
										    'spine_width': 1,
									        'hspace': 0.1,
										    'line_width': 1,
										    'legend_length': 3,
										    'marker_size': 5,
										    'marker_edge_width': 1,
										    'marker_face_color': 'none',
											'labelpad': 3,
											'legend_frame_width': 0.5,
											'legend_edge_color': 'dimgray'}

		self.std_paper_1x1_partial_width = {'figsize': (8/inch, 6/inch),
										    'legend_size': 7,
										    'label_size': 7,
										    'tick_size': 7,
										    'tick_length': 3,
										    'tick_width': 1,
										    'tick_rotation': 45,
										    'spine_width': 1,
										    'hspace': 0.1,
										    'line_width': 1,
										    'legend_length': 3,
										    'marker_size': 5,
										    'marker_edge_width': 1,
										    'marker_face_color': 'none',
											'labelpad': 3,
											'legend_frame_width': 0.5,
											'legend_edge_color': 'dimgray'}

		self.std_paper_4x3_full_width = {'figsize': (16/inch, 14/inch),
							   			 'legend_size': 6,
							   			 'label_size': 6,
										 'tick_size': 6,
										 'tick_length': 1,
										 'tick_width': 0.5,
										 'tick_rotation': 45,
										 'spine_width': 0.5,
										 'hspace': 0.4,
										 'wspace': 0.05,
										 'line_width': 0.5,
										 'legend_length': 2,
										 'marker_size': 2,
										 'marker_edge_width': 0.5,
										 'marker_face_color': 'none',
										 'labelpad': 1,
										 'legend_frame_width': 0.25,
										 'legend_edge_color': 'dimgray'}
