class FigureFormatting:
	def __init__(self):
		inch = 2.54
		pres_scaler = 1.2

		self.styler = {'light': {'name': 'light',
								 'facecolor': 'white',
								 'axis_color': 'white',
								 'label_color': 'black',
								 'tick_color': 'black',
								 'tick_label_color': 'black',
								 'spine_color': 'black',
								 'axis_label_color': 'black',
								 'text_color': 'black',
								 'aidline_color': 'black',
								 'legend_text_color': 'black',
								 'legend_edge_color': 'black',
								 'legend_face_color': 'white',
								 'legend_framealpha': 0.8,
								 'legend_edge_color_rgba': (0, 0, 0, 0),
								 'legend_face_color_rgba': (1, 1, 1, 0.5)},
					   'dark': {'name': 'dark',
								'facecolor': 'black',
								'axis_color': 'black',
								'label_color': 'white',
								'tick_color': 'white',
								'tick_label_color': 'white',
								'spine_color': 'white',
								'axis_label_color': 'white',
								'text_color': 'white',
								'aidline_color': 'white',
								'legend_text_color': 'white',
								'legend_edge_color': 'white',
								'legend_face_color': 'black',
								'legend_framealpha': 0.5,
								'legend_edge_color_rgba': (1, 1, 1, 0),
								'legend_face_color_rgba': (0, 0, 0, 0.5)}}

		self.paper_full_width = {'fig_type': 'paper',
								 'figsize': (16/inch, 6/inch),
							     'legend_size': 8,
							   	 'label_size': 8,
								 'tick_size': 8,
								 'tick_length': 3,
								 'tick_width': 1,
								 'tick_rotation': 45,
								 'spine_width': 1,
								 'line_width': 1,
								 'legend_length': 3,
								 'labelpad': 3,
								 'legend_frame_width': 0.5,
								 'legend_edge_color': 'dimgray'}

		self.pres_full_width = {'fig_type': 'paper',
								'figsize': (pres_scaler*16/inch, pres_scaler*6/inch),
								'legend_size': 8,
								'label_size': 8,
								'tick_size': 8,
								'tick_length': 3,
								'tick_width': 0.5,   # decreased
								'tick_rotation': 45,
								'spine_width': 0.5,   # decreased
								'line_width': 1,
								'legend_length': 3,
								'labelpad': 3,
								'legend_frame_width': 0.5,
								'legend_edge_color': 'dimgray'}		# this has to be moved to styler

		self.std_paper_3x1_full_width = {'figsize': (16/inch, 12/inch),
							   			 'legend_size': 8,
							   			 'label_size': 8,
										 'tick_size': 8,
										 'tick_length': 3,
										 'tick_width': 1,
										 'tick_rotation': 45,
										 'spine_width': 1,
										 'hspace': 0.1,
										 'line_width': 1,
										 'legend_length': 3,
										 'labelpad': 3,
										 'legend_frame_width': 0.5,
										 'legend_edge_color': 'dimgray'}

		self.std_paper_3x1_partial_width = {'figsize': (10/inch, 12/inch),
							   			    'legend_size': 8,
							   			    'label_size': 8,
										    'tick_size': 8,
										    'tick_length': 3,
										    'tick_width': 1,
										    'tick_rotation': 45,
										    'spine_width': 1,
									        'hspace': 0.1,
										    'line_width': 1,
										    'legend_length': 3,
										    'marker_size': 5,
										    'marker_edge_width': 1,
										    'marker_face_color': 'none',
											'labelpad': 3,
											'legend_frame_width': 0.5,
											'legend_edge_color': 'dimgray'}

		self.std_paper_1x1_partial_width = {'figsize': (8/inch, 6/inch),
										    'legend_size': 7,
										    'label_size': 7,
										    'tick_size': 7,
										    'tick_length': 3,
										    'tick_width': 1,
										    'tick_rotation': 45,
										    'spine_width': 1,
										    'hspace': 0.1,
										    'line_width': 1,
										    'legend_length': 3,
										    'marker_size': 5,
										    'marker_edge_width': 1,
										    'marker_face_color': 'none',
											'labelpad': 3,
											'legend_frame_width': 0.5,
											'legend_edge_color': 'dimgray'}

		self.paper_4x3_full_width = {'figsize': (16/inch, 14/inch),
							   		 'legend_size': 6,
							   		 'label_size': 6,
									 'tick_size': 6,
									 'tick_length': 1,
									 'tick_width': 0.5,
									 'tick_rotation': 45,
									 'spine_width': 0.5,
									 'hspace': 0.4,
									 'wspace': 0.05,
									 'line_width': 0.5,
									 'legend_length': 2,
									 'marker_size': 2,
									 'marker_edge_width': 0.5,
									 'marker_face_color': 'none',
									 'labelpad': 1,
									 'legend_frame_width': 0.25,
									 'legend_edge_color': 'dimgray'}

		self.pres_4x3_full_width = {'figsize': (pres_scaler*16 / inch, pres_scaler*14 / inch),
									'legend_size': 6,
									'label_size': 6,
									'tick_size': 6,
									'tick_length': 1,
									'tick_width': 0.5,
									'tick_rotation': 45,
									'spine_width': 0.5,
									'hspace': 0.4,
									'wspace': 0.05,
									'line_width': 0.5,
									'legend_length': 2,
									'marker_size': 2,
									'marker_edge_width': 0.5,
									'marker_face_color': 'none',
									'labelpad': 1,
									'legend_frame_width': 0.15,
									'legend_edge_color': 'dimgray'}
